WiiLink24/web

public/locales/en/translation.json

Found some minor typos and grammar issues while browsing the website, so I decided to submit a PR to update the strings.

Minor typo and grammatical fixes

---

src/content/guide/2installation.md

Update installation guide

---

README.md
src/content/guide/3demae_install.md
src/content/guide/EVC_country_languages.md

this should be the last of the pull requests from me for the time being

fixed pictures in the food channel installation, and fixed the patcher link in readme.md 

---

astro-i18next.config.mjs
public/json/fr/goodies.json
public/json/fr/services.json
public/json/fr/team.json
public/locales/en/translation.json
public/locales/fr/translation.json
src/pages/fr/404.astro
src/pages/fr/eula/index.astro
src/pages/fr/extras/index.astro
src/pages/fr/guide/[slug].astro
src/pages/fr/guide/index.astro
src/pages/fr/index.astro
src/pages/fr/news/[slug].astro
src/pages/fr/news/index.astro
src/pages/fr/privacy-policy/index.astro
src/pages/fr/status/index.astro
src/pages/fr/tos/index.astro

Added french localization for the whole website (except content)

Add French localization

---

src/content/guide/demae.md
src/content/guide/digicam.md
src/content/guide/forecast.md
src/content/guide/kirbytv.md
src/content/guide/miicontest.md
src/content/guide/nintendochannel.md
src/content/guide/wiinoma.md

Fixes spelling and grammar mistakes, and updates the link to the Privacy Policy

Update bits + bobs

---

public/json/ca/team.json
public/json/de/team.json
public/json/en-GB/team.json
public/json/es-LAT/team.json
public/json/es/team.json
public/json/fr/team.json
public/json/it/team.json
public/json/ja/team.json
public/json/pt-BR/team.json
public/json/pt-PT/team.json
public/json/team.json

- changed linked images from discord profile pictures to ones that will always get the discord user's current profile picture using this [cool API from shig.co](<https://github.com/shigandco/average-discord-user>)
- cleaned some spacing within some titles across a few languages
- formatted each of them with prettier lol

changed discord links and some spacing in team members

---

public/json/team.json

Add my team listing

---

FQA.md
Install.md
Problemsolving.md
board.md
demae.md
digicam.md
dokodemo.md
evc.md
forecast.md
kirbytv.md
miicontest.md
news.md
nintendochannel.md
tvnotomo.md
wiinoma.md

Its what it says on the tin. This was painful lmao

Slightly Major Writing update

---

src/content/guide/Install.md

Added an additional step as well as specifying that the apps folder should be copied to the root of the SD card.

Improved instruction clarity for vWii users

---

src/content/guide/Install.md

This matches the name of the WAD the patcher now produces

Update WiiLink SPD to WiiLink Address Settings

---

src/components/Agreement.astro

Replaced "discord.com" with "discord.gg" to fix link

Fixed a small issue with the Discord link

---

src/content/guide/Install.md

This replaces the previous implementation of the patcher downloading a EULA wad.

Add instructions for system-channel-installer

---

src/content/guide/demae.md

The demae-support channel was on the old wiilink discord pre-merge, and isn't on the current server

Update demae-support to support-text

---

src/content/guide/vwii.md

Make it clear that all apps need to be extracted

Clear up vWii instructions

---

src/content/guide/Install.md
src/content/guide/dolphin.md
src/content/guide/vwii.md
src/content/guide/wii.md

Changed patcher executable file name to match current naming scheme, added warning box to direct users to Domino's guide if they want to use Food Channel - Domino's.

Guide corrections to make it more up-to-date

---

package-lock.json
src/layouts/Layout.astro

one day, i pray we are no longer dependent on fontawesome not committing tomfoolery

Fix: revert fontawesome url

---

src/content/guide/Problemsolving.md

- Adds the **_Invalid Wii Console_** Error for WiiLink Accounts

Add Troubleshooting Error

---

public/json/team.json

I couldn't think of a better name for this, so hopefully its not too confusing

Remove removed team member from team.json

---

src/components/Hero.astro

i forgor about the actual button people click last time :3

Fix main download button

---

src/content/guide/update.md

Line 48:
"If you're migrating from RiiConnect24, or otherwise don't know whichbchannels (...)" =>  "If you're migrating from RiiConnect24, or otherwise don't know which channels (...)"

Fixed a spelling mistake
